ts_list =[['Sunflower Seed', 'Mombasa : KEN', 'KEN', 1],
 ['Kilombero Rice', 'Arusha : TZA', 'TZA', 1],
 ['Red Bean', 'Nairobi : KEN', 'KEN', 1],
 ['Soya Bean', 'Arusha : TZA', 'TZA', 1],
 ['Millet Grain', 'Masindi : UGA', 'UGA', 1],
 ['Green Pea', 'Bujumbura : BDI', 'BDI', 1],
 ['Cowpea', 'Eldoret : KEN', 'KEN', 1],
 ['Chic Pea', 'Juba : SSD', 'SSD', 1],
 ['Rice', 'Goma : DRC', 'DRC', 1],
 ['Mbeya Rice', 'Arusha : TZA', 'TZA', 1],
 ['Cowpea', 'Gulu : UGA', 'UGA', 1],
 ['Mixed Beans', 'Bukavu : DRC', 'DRC', 1],
 ['Pigeon Pea', 'Arusha : TZA', 'TZA', 1],
 ['Red Bean', 'Ngozi : BDI', 'BDI', 1],
 ['Maize Flour', 'Bukavu : DRC', 'DRC', 1],
 ['Soya Bean', 'Kimironko : RWA', 'RWA', 1],
 ['Old Bean', 'Kimironko : RWA', 'RWA', 1],
 ['Yellow Bean', 'Kolwezi : DRC', 'DRC', 1],
 ['Imported Rice', 'Bujumbura : BDI', 'BDI', 1],
 ['Wheat', 'Gitega : BDI', 'BDI', 1],
 ['Dry Pea', 'Meru : KEN', 'KEN', 1],
 ['Cowpea', 'Kasese : UGA', 'UGA', 1],
 ['Maize Flour', 'Masindi : UGA', 'UGA', 1],
 ['Soya Bean', 'Kamembe : RWA', 'RWA', 1],
 ['Morogoro Rice', 'Dar Es Salaam : TZA', 'TZA', 1],
 ['Green Pea', 'Gitega : BDI', 'BDI', 1],
 ['Mbeya Rice', 'Dar Es Salaam : TZA', 'TZA', 1],
 ['Rice', 'Tunduma : TZA', 'TZA', 1],
 ['Old Bean', 'Tunduma : TZA', 'TZA', 1],
 ['Wheat', 'Mwanza : TZA', 'TZA', 1],
 ['Pigeon Pea', 'Ngozi : BDI', 'BDI', 1],
 ['Wheat', 'Goma : DRC', 'DRC', 1],
 ['Millet Grain', 'Goma : DRC', 'DRC', 1],
 ['Mbeya Rice', 'Iringa : TZA', 'TZA', 1],
 ['Cowpea', 'Mbale : UGA', 'UGA', 1],
 ['Millet Grain', 'Mombasa : KEN', 'KEN', 1],
 ['Millet Grain', 'Nairobi : KEN', 'KEN', 1],
 ['Pigeon Pea', 'Nairobi : KEN', 'KEN', 1],
 ['White Millet', 'Tunduma : TZA', 'TZA', 1],
 ['Imported Rice', 'Uvira : DRC', 'DRC', 1],
 ['Rice', 'Kimironko : RWA', 'RWA', 1],
 ['Pigeon Pea', 'Makueni : KEN', 'KEN', 1],
 ['Rice', 'Gitega : BDI', 'BDI', 1],
 ['Mbeya Rice', 'Mbeya : TZA', 'TZA', 1],
 ['Wheat', 'Iringa : TZA', 'TZA', 1],
 ['Maize Flour', 'Kolwezi : DRC', 'DRC', 1],
 ['Maize Bran', 'Masindi : UGA', 'UGA', 1],
 ['Green Gram', 'Mwanza : TZA', 'TZA', 1],
 ['Kahama Rice', 'Arusha : TZA', 'TZA', 1],
 ['Pearl Millet', 'Arusha : TZA', 'TZA', 1],
 ['Green Pea', 'Nairobi : KEN', 'KEN', 1],
 ['Kidney Bean', 'Mbeya : TZA', 'TZA', 1],
 ['Morogoro Rice', 'Arusha : TZA', 'TZA', 1],
 ['Maize Bran', 'Mbale : UGA', 'UGA', 1],
 ['Groundnut', 'Nairobi : KEN', 'KEN', 1],
 ['Wheat', 'Mbeya : TZA', 'TZA', 1],
 ['Kidney Bean', 'Tunduma : TZA', 'TZA', 1],
 ['Imported Rice', 'Nakuru : KEN', 'KEN', 1],
 ['Green Pea', 'Ngozi : BDI', 'BDI', 1],
 ['Wheat Flour', 'Kasumbalesa : DRC', 'DRC', 1],
 ['Groundnut', 'Mwanza : TZA', 'TZA', 1],
 ['Wheat', 'Nairobi : KEN', 'KEN', 1],
 ['Wheat', 'Mombasa : KEN', 'KEN', 1],
 ['Imported Rice', 'Kampala : UGA', 'UGA', 1],
 ['Rice', 'Nairobi : KEN', 'KEN', 1]]
